setwd("F:/mycode")
install.packages("ggplot2")
install.packages("ggsignif")
install.packages("ggsci")
install.packages("reshape2")
install.packages("ggprism")
install.packages("patchwork")
install.packages("tidyverse")
install.packages("vegan")
install.packages("devtools")
install.packages("ggbiplot")
install.packages("scatterplot3d")
install.packages("ade4")
install.packages("microeco")

install.packages("BiocManager")
library(BiocManager)
BiocManager::install("ggtree")

install.packages("readxl")

source("alpha_divanalysis.R")
source("microdat_ready.R")
source("betadiversity_binary.R")
source("betadiversity_multi.R")
source("function_lefse.R")
source("micro_lefse.R")
source("microcomp_barplot.R")
